name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp_version}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp_version: ['24.0.4', '23.3.4.5']
        elixir: ['1.12.2', '1.11.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir}}

      - name: Elixir cache
        uses: actions/cache@v2
        id: elixir-build-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.otp_version }}-${{ matrix.elixir }}-${{ env.MIX_ENV }}-elixir_cache-mixlockhash-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp_version }}-${{ matrix.elixir }}-${{ env.MIX_ENV }}-elixir_cache-

      - name: Mix dependencies
        if: steps.elixir-build-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile dependencies
        if: steps.elixir-build-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Compile
        run: mix compile --warnings-as-errors --force

      - name: Check formatting
        run: mix format --check-formatted

      - name: Tests
        run: mix test

      - name: Dialyzer
        run: mix dialyzer
